# Use root/example as user/password credentials
version: '3.1'

services:

  mysqldb:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose: 
      - "3306"
    ports: 
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: adminSA

  backend-node:
    build: .
    expose: 
      - "3636"
    ports: 
      - 3636:3636
    depends_on:
      - mysqldb